version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_DATABASE: wordpress
     env_file:
       - ./secrets.env

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
     env_file:
       - ./secrets.env
     volumes: 
       - ./themes/:/var/www/html/wp-content/themes/
       - ./Search-Replace-DB-master/:/var/www/html/temporary/Search-Replace-DB-master/
volumes:
    db_data: {}
